// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "lambda-swappi-api",
    "version": "1"
  },
  "paths": {
    "/peoples": {
      "post": {
        "summary": "addPeople",
        "description": "",
        "operationId": "addPeople.post./peoples",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/peoples/{number}": {
      "get": {
        "summary": "getPeople",
        "description": "",
        "operationId": "getPeople.get./peoples/{number}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "number",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};